openapi: 3.0.1
info:
  title: Merchant Identifier Referance API
  description: Mastercard DW EDS Merchant Identifier Refereance API
  termsOfService: "https://developer.mastercard.com/terms-of-use"
  contact:
    name: MasterCard Developers
    url: https://developer.mastercard.com/
    email: developers@mastercard.com
  version: 1.0.0
servers:
  - url: https://api.mastercard.com/merchant-identifier
    description: Production server (uses live data)
  - url: https://sandbox.api.mastercard.com/merchant-identifier #https://sandbox.api.mastercard.com/merchant-identifier
    description: Sandbox server (testing environment)
tags:
  - name: Merchants
    description: API for Merchant Identifier
paths:
  /merchants:
    get:
      tags:
        - Merchants
      summary: Get merchants for a given merchant descriptor
      description: Returns a list merchants for a given merchant descriptor
      operationId: getMerchants
      parameters:
        - $ref: '#/components/parameters/MerchantDescriptorParam'
        - $ref: '#/components/parameters/MatchTypeParam'
      responses:
        '200':
          $ref: '#/components/responses/MerchantList'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  /merchants-by-card-acceptor-ids:
    get:
      tags:
        - Merchants
      summary: Get merchants for a given merchant card acceptor id
      description: Returns a list merchants for a given card acceptor id
      operationId: getMerchantByCardAcceptorId
      parameters:
        - $ref: '#/components/parameters/MerchantCardAcceptorIdParam'
      responses:
        '200':
          $ref: '#/components/responses/MerchantByCardAcceptorIdList'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
components:
  parameters:
    MerchantDescriptorParam:
      name: merchant_descriptor
      in: query
      description: Merchant Descriptor
      required: true
      schema:
        type: string
      example: 'DOLIUMPTYLTDWELSHPOOLWA'
    MatchTypeParam:
      name: match_type
      in: query
      description: The type of match to perform
      schema:
        type: string
        default: 'ExactMatch'
      example: 'ExactMatch'
    MerchantCardAcceptorIdParam:
      name: card_acceptor_id
      in: query
      description: Card Acceptor Id
      required: true
      schema:
        type: string
      example: 'C928456'
  schemas:
    Address:
      description: Available information for this Address such as the street, city, country, country subdivision an postal code.
      type: object
      properties:
        city:
          type: string
          description: Name of the city or town where the merchant is located
          example: WELSHPOOL
        country:
          $ref: '#/components/schemas/Country'
        countrySubdivision:
          $ref: '#/components/schemas/CountrySubDivision'
        line1:
          type: string
          description: Line 1 of the street address of the merchant. Usually includes the street number and name
          example: UNIT 2 248 WELSHPOOL RD
        line2:
          type: string
          description: Line 2 of the street address, usually an apartment number or suite number
          example: "12"
        postalCode:
          type: string
          description: The zip code or postal code for a merchant
          example: "6106"
      example:
        country:
          code: 'AUS'
          name: 'Australia'
        countrySubdivision:
          code: 'WA'
          name: 'Western Australia'
        line1: 'UNIT 2 248 WELSHPOOL RD'
        line2: '12'
        postalCode: '6106'
    Country:
      description: Available information the Country such as the name and code
      type: object
      properties:
        code:
          type: string
          description: Three digit alpha country code as defined in ISO 3166-1
          example: 'AUS'
        name:
          type: string
          description: Name of the country
          example: 'Australia'
      example:
        Country:
          code: 'AUS'
          name: 'Australia'
    CountrySubDivision:
      description: Available information the Country Subdivision such as the name and code
      type: object
      properties:
        code:
          type: string
          description: Abbreviated code for the state or province
          example: 'WA'
        name:
          type: string
          description: Name of the state or province
          example: 'Western Australia'
      example:
        CountrySubDivision:
          code: 'WA'
          name: 'Western Australia'
    Error:
      description: Details of the error condition such as the source of the error, reason code for the error,
        if the error is recoverable, and details about the error
      required:
        - Description
        - ReasonCode
        - Recoverable
        - Source
      type: object
      properties:
        Source:
          description: The application that generated this error
          type: string
          minLength: 0
          maxLength: 150
          example: 'merchantid'
        ReasonCode:
          description: A unique constant identifying the error case encountered during transaction processing
          type: string
          minLength: 0
          maxLength: 150
          example: 'TOO_MANY_MATCHES'
        Description:
          description: Short description of the ReasonCode field
          type: string
          minLength: 0
          maxLength: 150
          example: 'Too many matches found.  Please refine search input'
        Recoverable:
          description: Indicates whether this error will always be returned for this request, or retrying could change the outcome
          type: boolean
          example: 'false'
        Details:
          description: Description of the issue
          example: 'The search resulted in too many matches'
          type: string
          minLength: 0
          maxLength: 150
          nullable: true
    ErrorResponse:
      description: Only returned in the event of an error condition
      required:
        - Errors
      type: object
      properties:
        Errors:
          $ref: '#/components/schemas/Errors'
    Errors:
      description: 'Only returned in the event of an error condition'
      required:
        - Error
      type: object
      properties:
        Error:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: 'An error object'
          example:
            - Error:
                Source: merchant_descriptor
                ReasonCode: INVALID_INPUT_VALUE
                Description: "merchant_descriptor must be greater than 10 characters"
                Recoverable: false
                Details: null
      example:
        Errors:
          - Error:
              Source: merchant_descriptor
              ReasonCode: INVALID_INPUT_VALUE
              Description: "merchant_descriptor must be greater than 10 characters"
              Recoverable: false
              Details: null
    Merchant:
      description: Available information the merchant such as Address, matchConfidenceScore, and locationId
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        brandName:
          type: string
          description: The brand name of the merchant
          example: 'DOLIUM PTY LTD'
        merchantDescriptor:
          type: string
          description: Descriptor for the merchant provided by the Merchant Service
            Provider(MSP)
          example: 'DOLIUMPTYLTDWELSHPOOLWA'
        legalCorporateName:
          type: string
          description: Corporate legal name of the merchant
          example: DOLIUM PTY LTD
        locationId:
          type: integer
          description: Merchant specific location identifier
          format: int32
          example: 344147943
        matchConfidenceScore:
          type: integer
          description: Confidence score (%) to help clients understand the quality
            of the search results
          format: int32
          example: 100
        merchantCategory:
          type: string
          description: Merchant category code and description associated with the
            merchant category code for the merchant
          example: '5533 - AUTOMOTIVE PARTS  ACCESSORIES STORES'
        merchantDbaName:
          type: string
          description: The business name of the merchant
          example: DOLIUM PTY LTD
        phoneNumber:
          type: string
          description: phoneNumber
          example: "893582575"
        soleProprietorName:
          type: string
          description: The name of the proprietor
          example: Sole Proprietor Name example
    MerchantByCardAcceptorId:
      description: Available information the merchant such as Address, matchConfidenceScore, and locationId
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        brandName:
          type: string
          description: The brand name of the merchant
          example: 'DOLIUM PTY LTD'
        cardAcceptorId:
          type: string
          description: The Card Acceptor ID assigned by the acquirer
          example: 'C928456'
        legalCorporateName:
          type: string
          description: Corporate legal name of the merchant
          example: DOLIUM PTY LTD
        locationId:
          type: integer
          description: Merchant specific location identifier
          format: int32
          example: 344147943
        merchantCategory:
          type: string
          description: Merchant category code and description associated with the
            merchant category code for the merchant
          example: '5533 - AUTOMOTIVE PARTS  ACCESSORIES STORES'
        merchantDbaName:
          type: string
          description: The business name of the merchant
          example: DOLIUM PTY LTD
        phoneNumber:
          type: string
          description: phoneNumber
          example: "893582575"
        soleProprietorName:
          type: string
          description: The name of the proprietor
          example: Sole Proprietor Name example
    MerchantList:
      description: List of merchants
      type: object
      properties:
        merchants:
          type: array
          description: merchants
          items:
            $ref: '#/components/schemas/Merchant'
          example:
            -  matchConfidenceScore: 100
               address:
                 line1: 'UNIT 2 248 WELSHPOOL RD'
                 line2: '12'
                 city : 'Springfield'
                 postalCode: '6106'
                 country:
                   code: 'AUS'
                   name: 'Australia'
                 countrySubdivision:
                   code: 'WA'
                   name: 'Western Australia'
               brandName: 'DOLIUM PTY LTD'
               phoneNumber: "893582575"
               merchantCategory: '5533 - AUTOMOTIVE PARTS  ACCESSORIES STORES'
               merchantDbaName: 'DOLIUM PTY LTD'
               merchantDescriptor: 'DOLIUMPTYLTDWELSHPOOLWA'
               legalCorporateName: 'DOLIUM PTY LTD'
               locationId: 344147943
               soleProprietorName: 'Joe'
    MerchantByCardAcceptorIdList:
      description: List of merchants
      type: object
      properties:
        merchants:
          type: array
          description: merchants
          items:
            $ref: '#/components/schemas/MerchantByCardAcceptorId'
          example:
            -  address:
                 line1: 'UNIT 2 248 WELSHPOOL RD'
                 line2: '12'
                 city : 'Springfield'
                 postalCode: '6106'
                 country:
                   code: 'AUS'
                   name: 'Australia'
                 countrySubdivision:
                   code: 'WA'
                   name: 'Western Australia'
               brandName: 'DOLIUM PTY LTD'
               phoneNumber: "893582575"
               merchantCategory: '5533 - AUTOMOTIVE PARTS  ACCESSORIES STORES'
               merchantDbaName: 'DOLIUM PTY LTD'
               cardAcceptorId: 'C928456'
               legalCorporateName: 'DOLIUM PTY LTD'
               locationId: 344147943
               soleProprietorName: 'Joe'
  responses:
    MerchantList:
      description: Information for this merchant identifier
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantList'
    MerchantByCardAcceptorIdList:
      description: Information for this merchant identifier
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantByCardAcceptorIdList'
    BadRequestError:
      description: Something was wrong with the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: merchant_descriptor
                  ReasonCode: INVALID_INPUT_VALUE
                  Description: "merchant_descriptor must be greater than 10 characters"
                  Recoverable: false
                  Details: null
    UnauthorizedError:
      description: Authentication information was missing or invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source: merchantidentifier-api
                  ReasonCode: UNAUTHORIZED
                  Description: "We couldn't recognize you"
                  Recoverable: false
                  Details: "Full authentication is required to access this resource"
    ForbiddenError:
      description: Insufficient permissions for interacting with the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            Errors:
              - Error:
                  Source:  merchantidentifier-api
                  ReasonCode: PERMISSION_DENIED
                  Description: "You don't seem authorized to do that"
                  Recoverable: false
                  Details: "Reading merchant information requires readonly permissions"